const ROORO_CODE = {
    UNEXPECTED: 1,
    PACKAG_DECODE: 2,
    PACKAG_ENCODE: 3,

    FAILED_ENCRYPT: 4,
    FAILED_VERIFICATION: 5,
    EXPIRED: 6,
    NOT_IMPLEMENTED: 7,
    OUT_OF_RANGE: 8,
    SKIP: 9,
    REPEAT_ACTION: 10,
    NO_SETUP_METHOD:11,

    NO_OPEN: 1000,
    NO_MONEY: 1001,
    NO_TARGET: 1002,
    NO_MATCH: 1003,
    INCORRECT_STATE: 1004,
    NO_PLAYER: 1005,
    NO_TABLE: 1006,
    REPEAT_TARGET: 1007
};
Object.freeze(ROORO_CODE);

module.exports = ROORO_CODE;